version: '3.8'

services:
  app:
    image: mcr.microsoft.com/playwright:focal
    container_name: bookstore-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm ci && npm run build && npm run start"

  tests:
    image: mcr.microsoft.com/playwright:focal
    depends_on:
      - app
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npx wait-on http://app:3000 && npx playwright test --reporter=list"
